import argparse
import csv
import os
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

try:
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
except Exception:  # pragma: no cover
    Credentials = None
    InstalledAppFlow = None
    build = None


SCOPES = ["https://www.googleapis.com/auth/calendar.events"]


def parse_start_datetime(s: str, default_tz: timezone) -> datetime:
    # Expect either:
    # - "YYYY-MM-DDTHH:MM:SS" (interpreted in default_tz)
    # - "YYYY-MM-DDTHH:MM:SSZ" (UTC)
    if s.endswith("Z"):
        return datetime.fromisoformat(s.replace("Z", "+00:00"))
    dt = datetime.fromisoformat(s)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=default_tz)
    return dt


def build_calendar_service(credentials_json: Path, token_json: Path):
    if Credentials is None or InstalledAppFlow is None or build is None:
        raise RuntimeError("Google API libraries not installed.")
    creds = None
    if token_json.exists():
        creds = Credentials.from_authorized_user_file(str(token_json), SCOPES)

    if not creds or not creds.valid:
        flow = InstalledAppFlow.from_client_secrets_file(str(credentials_json), SCOPES)
        creds = flow.run_local_server(port=0)
        token_json.parent.mkdir(parents=True, exist_ok=True)
        token_json.write_text(creds.to_json(), encoding="utf-8")

    return build("calendar", "v3", credentials=creds)


def main() -> None:
    parser = argparse.ArgumentParser(description="Phase 9: schedule Google Calendar interviews with Meet.")
    parser.add_argument(
        "--qualified_csv",
        type=str,
        default=r"c:\Users\arunk\OneDrive\Desktop\files\candidate_screening_platform\data\qualified_candidates.csv",
    )
    parser.add_argument(
        "--calendar_id",
        type=str,
        default="primary",
        help="Google Calendar ID (use 'primary' for the authenticated user).",
    )
    parser.add_argument(
        "--start_datetime",
        type=str,
        default="2026-03-23T10:00:00Z",
        help="Interview start datetime in ISO format. Example: 2026-03-23T10:00:00Z",
    )
    parser.add_argument(
        "--slot_minutes",
        type=int,
        default=30,
        help="Minutes per interview slot.",
    )
    parser.add_argument(
        "--timezone",
        type=str,
        default="UTC",
        help="Only used for interpreting naive start_datetime; actual events use RFC3339 timestamps.",
    )
    parser.add_argument(
        "--credentials_json",
        type=str,
        default=r"c:\Users\arunk\OneDrive\Desktop\files\candidate_screening_platform\google_oauth_credentials.json",
        help="OAuth client credentials JSON downloaded from Google Cloud Console.",
    )
    parser.add_argument(
        "--token_json",
        type=str,
        default=r"c:\Users\arunk\OneDrive\Desktop\files\candidate_screening_platform\google_oauth_token.json",
        help="Where to store OAuth tokens after first run.",
    )
    parser.add_argument(
        "--out_csv",
        type=str,
        default=r"c:\Users\arunk\OneDrive\Desktop\files\candidate_screening_platform\data\interview_schedule.csv",
    )
    args = parser.parse_args()

    qualified = pd.read_csv(args.qualified_csv)
    required = {"Candidate ID", "Name", "Email"}
    missing = [c for c in required if c not in qualified.columns]
    if missing:
        raise ValueError(f"qualified_candidates.csv missing columns: {missing}")

    default_tz = timezone.utc
    start_dt = parse_start_datetime(args.start_datetime, default_tz)

    credentials_json = Path(args.credentials_json)
    token_json = Path(args.token_json)

    dry_run = not credentials_json.exists() or build is None

    if dry_run:
        service = None
    else:
        service = build_calendar_service(credentials_json, token_json)

    out_rows = []
    for i, row in qualified.reset_index(drop=True).iterrows():
        cand_id = row["Candidate ID"]
        name = row["Name"]
        email = row["Email"]

        event_start = start_dt + timedelta(minutes=i * args.slot_minutes)
        event_end = event_start + timedelta(minutes=args.slot_minutes)

        event = {
            "summary": f"AI Engineering Interview - {name}",
            "description": "Interview invitation generated by AI Candidate Screening Platform.\n\n(Automated Meet link included.)",
            "start": {"dateTime": event_start.isoformat(), "timeZone": args.timezone},
            "end": {"dateTime": event_end.isoformat(), "timeZone": args.timezone},
            "attendees": [{"email": email}],
            "conferenceData": {
                "createRequest": {
                    "requestId": str(uuid.uuid4()),
                    "conferenceSolutionKey": {"type": "hangoutsMeet"},
                }
            },
        }

        if dry_run:
            out_rows.append(
                {
                    "Candidate ID": cand_id,
                    "Name": name,
                    "Email": email,
                    "start": event_start.isoformat(),
                    "end": event_end.isoformat(),
                    "mode": "dry_run",
                    "event_id": "",
                    "meet_link": "",
                }
            )
        else:
            created = (
                service.events()
                .insert(
                    calendarId=args.calendar_id,
                    body=event,
                    conferenceDataVersion=1,
                    sendUpdates="all",
                )
                .execute()
            )
            meet_link = ""
            conf = created.get("conferenceData") or {}
            meet_link = (conf.get("entryPoints") or [{}])[0].get("uri", "") if conf else ""

            out_rows.append(
                {
                    "Candidate ID": cand_id,
                    "Name": name,
                    "Email": email,
                    "start": event_start.isoformat(),
                    "end": event_end.isoformat(),
                    "mode": "scheduled",
                    "event_id": created.get("id", ""),
                    "meet_link": meet_link,
                }
            )

    Path(args.out_csv).parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(out_rows).to_csv(args.out_csv, index=False)
    print(f"Wrote interview schedule to {args.out_csv} (dry_run={dry_run})")


if __name__ == "__main__":
    main()

